name: rating_app
description: Rate miscadlasdls things.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  dio: ^4.0.6
  json_annotation: ^4.7.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  text_scroll: ^0.1.1
  marquee: ^2.2.3
  assorted_layout_widgets: ^7.0.0
  infinite_scroll_pagination: ^3.2.0
  supabase_flutter: ^1.0.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 600
        - asset: fonts/Poppins-Italic.ttf
          style: italic
  assets:
    - assets/